title: Marvel Snap 情報局
description: Marvel Snapの情報サイト　定期的に更新します
theme: minima
minima:
  skin: classic  # dark, auto, classic など
  social_links:
    twitter: your_twitter
    github: your_github
include:
  - pages
