title: マーベルスナップ攻略ブログ｜最強デッキ・イベント最新情報まとめ
description: マーベルスナップ（マベスナ）の最新情報・カード一覧を掲載！最強デッキ、メタ変化、ランク戦のコツなど初心者も上級者にもためになる情報が満載！
remote_theme: jekyll/minima
baseurl: "/marvelsnap.github.io"  # リポジトリ名と合わせる！
url: "https://marvel-otaku.github.io"




minima:
  skin: classic  # dark, auto, classic など
  social_links:
    twitter: your_twitter
    github: your_github

collections:
  pages:
    output: true
    permalink: /:path/

sass:
  sass_dir: _sass
  style: compressed  # もしくは expanded（デバッグ用）

